### ISSUE TITLE
8.1 emulator - Android restarts every few minutes

### ISSUE THREAD

**Issue by pawelus** [budtmo/docker-android#125]
Operating System: 
CentOS 7

Docker Image:
**butomo1989/docker-android-x86-8.1**

Docker Version:  
18.06.1-ce

Docker-compose version (Only if you use it):  
1.21.2, build a133471

Docker Command to start docker-android:  
docker-compose
  
## Expected Behavior
Android should not restart when performing actions (e.g. opening Chrome or Settings)

## Actual Behavior
Android restarts in emulator at random moments. Sometimes it's enough to open settings and Android will restart. I can't get it to work for more than 5 minutes without a restart
This doesn't happen on 7.1.1 image

## Docker compose file
```
version: "3"

services:
  selenium-hub:
    image: selenium/hub:3.14.0-beryllium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  
  android_web:
    image: butomo1989/docker-android-x86-8.1
    privileged: true
    depends_on: 
      - selenium-hub
    ports:
      - "6080:6080"
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=True
      - APPIUM=True
      - SELENIUM_HOST=selenium-hub
      - MOBILE_WEB_TEST=True
      - AUTO_RECORD=False
```
