### ISSUE TITLE
Can't communicate with host adb

### ISSUE THREAD

**Issue by stephane-r** [budtmo/docker-android#148]
Hi community !

I've an small problem about the communication about host and emulator container. My problem : 

**Operating System**: Ubuntu 18
**Docker Image**: budtmo/docker-android-x86-9.0
**Docker Version**:  18.09.1
**Docker-compose version**:  1.23.2
**Docker Command to start docker-android**:  `USER_ID=$(USER_ID) docker-compose -p project_name run --rm --service-ports emulator`

My docker-compose file : 

```
version: '3'

services:
  yap:
    build: ./config/docker/nodejs
    container_name: my_container_name
    environment:
      - LOCAL_USER_ID=$USER_ID
    ports:
      - 8081:8081
      - 3000:3000
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - $PWD:/app
    privileged: true

  emulator:
    image: budtmo/docker-android-x86-$EMULATOR_ANDROID_VERSION
    container_name: emulator_android
    environment:
      - DEVICE=$EMULATOR_DEVICE_NAME
    ports:
      - 6080:6080
      - 5554:5554
      - 5555:5555
      - 4723:4723
    privileged: true
```
  
## Expected Behavior
I would like run React-Native app on Android emulator

## Actual Behavior
After connected adb to emulator container and running Android App, i've an erreur about development server not found.

I've been the build successful message : `Running /opt/android/platform-tools/adb -s 172.20.0.2:5555 reverse tcp:8081 tcp:8081`

![image](https://user-images.githubusercontent.com/4712791/54539656-d2ad3700-4996-11e9-98a0-786a98efab53.png)

It looks like the container of the emulator can not communicate with the host `adb` ?

I don't know if the problem is with React-Native ... but if i try to run my App on real device, i've no problem.
