### ISSUE TITLE
Run docker-android on top od k8s

### ISSUE THREAD

**Issue by maauso** [budtmo/docker-android#160]
Operating System: 
Kubernetes on to of Amazon Linux 2

Docker Image:
butomo1989/docker-android-x86-7.1.1

Docker Version:  
17.06

Docker-compose version (Only if you use it):  
we are not using

K8S Yaml to start docker-android:  
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: android
  namespace: selenium
  labels:
    app: selenium
    environment: stg
    role: qa
    service: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: android
  template:
    metadata:
      labels:
        app: android
    spec:
      containers:
      - name: android
        image: butomo1989/docker-android-x86-7.1.1
        resources:
          limits:
            memory: "2048Mi"
            cpu: "500m"
        securityContext:
          privileged: true
        ports:
        - containerPort: 6080
          name: port1
        - containerPort: 4723
          name: port2
        - containerPort: 5554
          name: port3
        - containerPort: 5555
          name: port4
        - containerPort: 5037
          name: port5
        env:
        - name: DEVICE
          value: "Nexus 5"
        - name: APPIUM
          value: "true"
        - name: CONNECT_TO_GRID
          value: "  true"
        - name: APPIUM_HOST
          value: "android.selenium"
        - name: APPIUM_PORT
          value: "4723"
        - name: SELENIUM_HOST
          value: "selenium-selenium-hub.selenium"
        - name: SELENIUM_PORT
          value: "4444"        
```
  
## Expected Behavior
Run docker-android on top of EKS

## Actual Behavior
The container can connect to the selenium hub, but when we want to launch the test we found the error
```
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
root@android-766c9c5f58-2wknl:~#
```
_full log attached_ 
[docker-android.stdout.log](https://github.com/budtmo/docker-android/files/3216884/docker-android.stdout.log)

Also, When we launch the test then we encountered an error in the `appium.log`
```
Could not find a connected Android device
```

We are running this docker on top of EKS it shouldn't be a problem, but do you have some documentation or workaround to do it?
