### ISSUE TITLE
Question -> Is it possible to use Chrome browser for any other platforms but 7.0 & 7.1.1?

### ISSUE THREAD

**Issue by mcopjan** [budtmo/docker-android#204]
I am using the following docker compose file 

```
version: '3'

services:
  selenium_hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  emulator:
    image: budtmo/docker-android-x86-8.1
    privileged: true
    depends_on:
      - selenium_hub
    ports:
      - 6080
    environment:
      - DEVICE=Samsung Galaxy S10
      - CONNECT_TO_GRID=True
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=false
      - BROWSER=chrome
```

I have noticed the note in https://github.com/budtmo/docker-android/blob/master/docker-compose.yml saying:
'Chrome browser exists only for version 7.0 and 7.1.1'

Is this still a thing? I am asking because I would prefer testing in Chrome and I can see it is installed in the emulator. I can also see there is 'ARG BROWSER=android' in https://microbadger.com/images/budtmo/docker-android-x86-8.1

But with the mentioned compose file above I can still see emulator is registered with the hub with the following capabilities: Capabilities {**browserName: android**, deviceName: samsung_galaxy_s10_8.1, maxInstances: 1, platform: ANDROID, platformName: Android, seleniumProtocol: WebDriver, server:CONFIG_UUID: e366fd25-d5c9-41a8-b686-c24..., version: 8.1}
