### ISSUE TITLE
Long running emulator becomes unhealthy - :glCheckFramebufferStatus:733 error 0x500

### ISSUE THREAD

**Issue by mcopjan** [budtmo/docker-android#205]
## 🐛 Bug Report

Operating System: 
Linux 3.10.0-1062.1.1.el7.x86_64 x86_64

Docker compose:

```
version: '2'

services:
  selenium_hub:
    image: selenium/hub
    restart: unless-stopped
    ports:
      - "4444:4444"

  emulator:
    image: budtmo/docker-android-x86-8.1
    restart: unless-stopped
    privileged: true
    depends_on:
      - selenium_hub
    ports:
      - 6080
      - 5554
      - 5555
    environment:
      - DEVICE=Samsung Galaxy S10
      - CONNECT_TO_GRID=True
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=true
```

Docker Version:  
Docker version 19.03.2, build 6a30dfc
 
## Expected Behavior
When I leave my selenium grid with emulators running for longer period they should still be in 'healthy' state

## Actual Behavior
I left my emulators up and running overnight (without using them for anything). After 12 hours I can see one of the containers became unhealthy with the following error 
![image](https://user-images.githubusercontent.com/20699180/67266801-f5617a00-f4a8-11e9-8b66-3da550730efa.png)

```
[root@uiplinfdoc019 martinco]# docker exec -it docker_emulator_2 tail -f /var/log/supervisor/docker-android.stderr.log
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500
/buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glCheckFramebufferStatus:733 error 0x500

```

System resources does not seem to be fully depleted.
![image](https://user-images.githubusercontent.com/20699180/67266790-ee3a6c00-f4a8-11e9-8e1d-1343614af2f5.png)
