### ISSUE TITLE
[🐛 Bug ]: Emulator is at Booting status forever

### ISSUE THREAD

**Issue by SudhanvaManjunath** [budtmo/docker-android#381]
### Operating System

Ubuntu

### Docker Image

budtmo/docker-android:emulator_13.0

### Expected behaviour

The emulator should be launched successfully

### Actual behaviour

The emulator is stuck at BOOTING status

### Logs

When I start the emulator via docker-compose file, the emulator is never displayed. Just the background.

```
version: "3"

services:
 samsung_galaxy_13.0:
  image: budtmo/docker-android:emulator_13.0
  deploy:
   resources:
    limits:
     cpus: '8'
     memory: 10000M
    reservations:
     cpus: '8'
     memory: 10000M
  privileged: true
  ports:
   - 4723:4723
   - 5555:5555
   - 9000:9000
   - 6080:6080
  volumes:
   - ./video-samsung_13.0:/tmp/video
  environment:
   - WEB_VNC=true
   - WEB_LOG= true
   - EMULATOR_DEVICE=Samsung Galaxy S10
   - APPIUM=true
   - EMULATOR_ADDITIONAL_ARGS="-gpu swiftshader_indirect -memory 8192 -netspeed full -accel on"
```

When I manually start the emulator it works fine.

<img width="1217" alt="image" src="https://github.com/budtmo/docker-android/assets/59612618/776184b1-4896-4b9c-82bc-e29a6ad05e4d">
