### ISSUE TITLE
[🐛 Bug ]: Device data reset when docker restart

### ISSUE THREAD

**Issue by sandyboxy** [budtmo/docker-android#395]
### Operating System

Ubuntu 22.04

### Docker Image

budtmo/docker-android:emulator_13.0

### Expected behaviour

Hello,
this is my docker-compose based on @SudhanvaManjunath [post](https://github.com/budtmo/docker-android/issues/381#issuecomment-1675066024)
```yaml
version: '3'
services:
  android-container:
    image: budtmo/docker-android:emulator_13.0
    #deploy:
    # resources:
    #  limits:
    #   cpus: '8'
    #   memory: 10000M
    #  reservations:
    #   cpus: '8'
    #   memory: 10000M
    privileged: true
    ports:
      - 4723:4723
      - 5555:5555
    #  - 9000
      - 6080:6080
    volumes:
      - ./video-samsung_13.0:/tmp/video
    environment:
      - EMULATOR_DEVICE="Samsung Galaxy S10"
     # - APPIUM=true
      - WEB_VNC=true
     # - WEB_LOG=true
     # - WEB_LOG_PORT=9000
    devices:
      - "/dev/kvm"
````

### Actual behaviour

When I stop docker and restart it I have a new phone with default settings and without my previous settings and data.

### Logs

Sometimes, when I restart docker I have the following errors:
```
docker-android-android-container-1  | 2023-11-09 15:42:32,344 INFO exited: device (exit status 1; not expected)
docker-android-android-container-1  | 2023-11-09 15:42:33,345 INFO gave up: device entered FATAL state, too many start retries too quickly
```
or
```
docker-android-android-container-1  | 2023-11-09 15:38:11,003 INFO exited: vnc_server (exit status 1; not expected)
docker-android-android-container-1  | 2023-11-09 15:38:11,009 INFO gave up: vnc_server entered FATAL state, too many start retries too quickly
```

**Comment by sandyboxy** [comment]
I also tried to mount volumes in this way but without success:
```
    volumes:
      - ./android:/root/.android/
      - ./android-emulator:/root/android_emulator
```

**Comment by Lumino2** [comment]
Having the same issue here. Tried it with privileged: true and the same volumes as @sandyboxy.

**Comment by sandyboxy** [comment]
I solved by mounting the following volumes:
```
- data:/home/androidusr
- root:/root
``` 
Hope this helps!

**Comment by Lumino2** [comment]
Thanks! @sandyboxy 
Here's a complete .yml file to anyone who wants to persist the data

version: '3.3'

services:
  docker-android:
	ports:
  	- '6080:6080'
  	- '5555:5555'
  	- '5554:5554'
	privileged: true
	environment:
  	- 'EMULATOR_DEVICE=Samsung Galaxy S10'
  	- WEB_VNC=true
	volumes:
  	- data:/home/androidusr
  	- root:/root
	devices:
  	- "/dev/kvm:/dev/kvm"
	container_name: android-container
	image: 'budtmo/docker-android:emulator_11.0'

volumes:
  data:
  root:

**Comment by llai-utexas** [comment]
I tried restarting with the same config file, but observed in `logs/device.stdout.log`. Not sure if anyone here got the same issue

```start_device()
  File "/home/androidusr/docker-android/cli/src/app.py", line 77, in start_device
    selected_device.start()
  File "/home/androidusr/docker-android/cli/src/device/emulator.py", line 160, in start
    self.change_permission()
  File "/home/androidusr/docker-android/cli/src/device/emulator.py", line 142, in change_permission
    subprocess.check_call(c, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo chown 1300:1301 /dev/kvm' returned non-zero exit status 1.```

**Comment by ErcinDedeoglu** [comment]
have same problem with @llai-utexas. Did you find a way?

**Comment by llai-utexas** [comment]
@ErcinDedeoglu I realize restarting the same docker container was the wrong way to keep the state. I follwed this suggestion here https://github.com/budtmo/docker-android/issues/129#issuecomment-493316051

>  I've found that if before stopping and rm the container I turn off the emulator phone on novnc, this issue goes away.

So what I did was using the volume mount confirguration listed above, but with a fresh docker container, while making sure the emulator was turned off in the last container, and the state was persisted

**Comment by ErcinDedeoglu** [comment]
@llai-utexas thanks a lot for your quick reply. It sounds like a lot of procedures to run for a docker container. I think this would be a maintenance failure for me. :)
I found this:
https://github.com/budtmo/docker-android/issues/364#issuecomment-1602755915
It says "you need to pay".
If the owner (@budtmo) of repository confirm, then I'll check paid option if it is well maintained.

**Comment by llai-utexas** [comment]
@ErcinDedeoglu I saw that comment as well. I had the pro version as well. While I would not run into the sudo issue, the emulator would not boot up properly. The only way that worked for me to persist the emulator state, was creating fresh container, for both pro and free versions

**Comment by bernatvadell** [comment]
I have managed to get the restart to work and persist the information. To do this I have created a Dockerfile that overwrites the original and restores the root user. I leave you the Dockerfile and docker-compose.yaml used in case it helps anyone.

Dockerfile
```Dockerfile
FROM budtmo/docker-android:emulator_11.0

USER root

RUN echo 'root:x:0:0:root:/root:/bin/bash' >> /etc/passwd

USER androidusr
```

docker-compose.yaml
```yaml
version: '3.7'

services:
  android-container:
    image: budtmo/docker-android:emulator_11.0
    build: 
      context: .
    container_name: android-container
    privileged: true
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    volumes:
      - data:/home/androidusr
      - root:/root
    ports:
      - "6080:6080"
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: always

volumes:
  data:
  root:
```

**Comment by dmzrui** [comment]
same problem, after using @bernatvadell 's method, appium still fail
![image](https://github.com/user-attachments/assets/c06448f4-e3b0-4751-bda2-bef736ec13ed)
the log of it is helpless:
`INFO App - env APPIUM cannot be found, Appium is not started!
`

**Comment by jamtheim** [comment]
OMG, this works for persisting data! Thank you so much! Dont forget to chmod +x on the run.sh before copy.

**Comment by juanbretti** [comment]
Thank you, @bernatvadell ! [This works](https://github.com/budtmo/docker-android/issues/395#issuecomment-2040219000). 
But...
Where are `data` and `root` are created on my local machine (the Docker host machine)?

> ```yaml
> volumes:
>   data:
>   root:
> ```

Thanks!

**Comment by juanbretti** [comment]
> OMG, this works for persisting data! Thank you so much! Dont forget to chmod +x on the run.sh before copy.

Thank you @jamtheim for the headsup.
The fill will end being:

Dockerfile
```dockerfile
FROM budtmo/docker-android:emulator_11.0

USER root

RUN echo 'root:x:0:0:root:/root:/bin/bash' >> /etc/passwd

USER androidusr

COPY run.sh /run.sh
RUN chmod +x /run.sh

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/run.sh"]
```

**Comment by juanbretti** [comment]
> the log of it is helpless:
> `INFO App - env APPIUM cannot be found, Appium is not started! `

Try using this `docker-compose.yaml`:

```yaml
version: '3.8'

services:
  android-container:
    build:
      context: .
    container_name: android-container
    # privileged: true
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S6
      - WEB_VNC=true
      - WEB_LOG=true
      - WEB_LOG_PORT=9000
      # - VNC_PASSWORD=yRBLPq4h5bVAzDT83f6jQX
      - ENV_LOG_PATH=/var/log/
      - APPIUM=true
    volumes:
      - data:/home/androidusr
      - root:/root
    ports:
      - "6080:6080"
      - "9005:9000"
      - "4723:4723"
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: always

volumes:
  data:
  root:
```

Notice I am adding:

**Comment by EugeneeT** [comment]
hi, i am trying to have automation run on this emulator. but i cant manage to make it restart after crashing or killing it. 
Best case would be that the emulator would restart automatically after a crash or kill without my interaction, since i need to run a app in the background to download some files when ever they are released. 

Did anyone manage something like that ? restarting the emulator and keeping files, i fail on even making it run again after a restart. 

compose: 
```
version: '3.7'

services:
 test2:
   build:
     context: .
   container_name: test2
   privileged: true
   environment:
     - EMULATOR_DEVICE=Samsung Galaxy S10
     - WEB_VNC=true
     - WEB_LOG=true
     - WEB_LOG_PORT=9000
     - VNC_PASSWORD=yRBLPq4h5bVAzDT83f6jQX
     - ENV_LOG_PATH=/var/log/
     - ANDROID_ARCH=x86_64
     - ANDROID_API=30
   volumes:
     - data:/home/androidusr
     - root:/root
     - ./downloads:/downloads
     - ./output:/output
     - ./archive:/archive
   ports:
     - "6080:6080"
     - "9005:9000"
   devices:
     - "/dev/kvm:/dev/kvm"
   deploy:
     resources:
       limits:
         memory: 4G
       reservations:
         memory: 2G
   shm_size: "1g"
   restart: always

volumes:
 data:
 root:

networks:
 default:
   driver: bridge
```

Dockerfile: 
```
FROM budtmo/docker-android:emulator_11.0
USER root
RUN echo 'root:x:0:0:root:/root:/bin/bash' >> /etc/passwd
USER androidusr
COPY run.sh /run.sh
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/run.sh"]
```

run.sh 
```
#!/bin/bash
rm -rf /home/androidusr/emulator/*.lock
/home/androidusr/docker-android/mixins/scripts/run.sh
```

```
#!/bin/bash

CONTAINER_NAME="test2"
VNC_PORT="6080"
LOG_PORT="9005"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

check_port() {
    local port=$1
    local max_attempts=$2
    local attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        if nc -z localhost $port; then
            return 0
        fi
        echo -n "."
        sleep 2
        attempt=$((attempt + 1))
    done
    return 1
}

echo "Starting container recovery tests..."

# Test container existence
echo -e "\n${YELLOW}1. Checking container status${NC}"
if ! docker ps -a | grep -q $CONTAINER_NAME; then
    echo -e "${RED}Container not found${NC}"
    exit 1
fi

# Record initial state
INITIAL_START_TIME=$(docker inspect -f '{{.State.StartedAt}}' $CONTAINER_NAME)
echo "Initial start time: $INITIAL_START_TIME"

# Simulate crash
echo -e "\n${YELLOW}2. Simulating container crash${NC}"
docker kill $CONTAINER_NAME
echo "Container killed. Waiting for restart..."

# Check restart (30 second timeout)
sleep 5
for i in {1..5}; do
    if docker ps | grep -q $CONTAINER_NAME; then
        echo -e "${GREEN}Container is running${NC}"
        break
    fi
    if [ $i -eq 5 ]; then
        echo -e "${RED}Container failed to restart${NC}"
        exit 1
    fi
    sleep 5
done

# Verify new start time
NEW_START_TIME=$(docker inspect -f '{{.State.StartedAt}}' $CONTAINER_NAME)
if [ "$INITIAL_START_TIME" != "$NEW_START_TIME" ]; then
    echo -e "${GREEN}Container successfully restarted with new start time${NC}"
else
    echo -e "${RED}Container start time unchanged - possible restart failure${NC}"
fi

# Check VNC port
echo -e "\n${YELLOW}3. Checking VNC port availability${NC}"
echo -n "Waiting for VNC port"
if check_port $VNC_PORT 15; then
    echo -e "\n${GREEN}VNC port $VNC_PORT is accessible${NC}"
else
    echo -e "\n${RED}VNC port $VNC_PORT not accessible after restart${NC}"
fi

# Check logs port
echo -e "\n${YELLOW}4. Checking logs port${NC}"
echo -n "Waiting for logs port"
if check_port $LOG_PORT 15; then
    echo -e "\n${GREEN}Logs port $LOG_PORT is accessible${NC}"
else
    echo -e "\n${RED}Logs port $LOG_PORT not accessible after restart${NC}"
fi

# Check Android emulator process
echo -e "\n${YELLOW}5. Checking emulator process${NC}"
sleep 10  # Give emulator time to start
if docker exec $CONTAINER_NAME ps aux | grep -q emulator; then
    echo -e "${GREEN}Emulator process is running${NC}"
else
    echo -e "${RED}Emulator process not found${NC}"
fi

echo -e "\n${GREEN}Testing complete!${NC}"
```
